### ISSUE TITLE
Use yaml or json format

### ISSUE THREAD

**Issue by domoritz** [steveharoz/open-access-vis#46]
It's pretty hard to edit the CSV online because it's difficult to match keys and values. A yaml file would be great! If you use jekyll, you could even read the data directly and the page could work without javascript. See https://jekyllrb.com/docs/datafiles/

**Comment by steveharoz** [comment]
It's a google drive [spreadsheet](https://docs.google.com/spreadsheets/d/11ZNUflBnK47ljl_g0NVJFntP1xb8qsSv-PcpinoeWRw/edit?usp=sharing) that I edit and export as a CSV whenever there are changes. Usability of the spreadsheet is the primary concern since the file is written manually rather than scraped.

**Comment by domoritz** [comment]
Ahh, awesome. I was trying to make changes to https://github.com/jamesscottbrown/open-access-eurovis but @jamesscottbrown hasn't enabled issues for the repo.

**Comment by jamesscottbrown** [comment]
I've enabled issues now: I thought they were already enabled by default, but apparently this has has changed and/or isn't true for forks.

Feel from to post an issue, email me or talk to me at a coffee break.

I also started off using Google Docs, but then switched to editing the CSV directly after encountering a silly issue (in the time field, the delimiter between the time and AM/PM was a character that looked like a space character, but was actually something else, which resulted in errors when D3 tried to parse it).
