### ISSUE TITLE
Materials for At a glance: pixel approximate entropy

### ISSUE THREAD

**Issue by sirrice** [steveharoz/open-access-vis#62]
At a Glance: Approximate Entropy as a Measure of Line Chart Visualization Complexity

1. Authors: Gabriel Ryan, Abigail Mosca, Remco Chang, Eugene Wu
2. Video: https://www.youtube.com/watch?v=TMlaBUzHt2Q
3. AuthorPDF: https://www.dropbox.com/s/9jipqhq1yqgn5yt/glance-infovis18-camera.pdf?dl=0
4. SourceMaterials: https://github.com/cudbg/pae

![image](https://user-images.githubusercontent.com/464518/48139598-e4f2c800-e274-11e8-9e2d-85b71bc4fc62.png)

**Comment by steveharoz** [comment]
Thanks Eugene. Is there PDF URL other than dropbox? I can't really link to any site that is not clearly controlled by an author due to IEEE's copyright rules. My suggestion is to post to a preprint repository (e.g., http://osf.io/preprints or http://arxiv.org). A personal or institution website would also work, but it doesn't have long-term reliability.

**Comment by sirrice** [comment]
Here it is on arxiv!
http://arxiv.org/abs/1811.03180

**Comment by steveharoz** [comment]
Nice!
