### ISSUE TITLE
Zenodo as a valid open access repo?

### ISSUE THREAD

**Issue by mjskay** [steveharoz/open-access-vis#66]
What about adding [zenodo](https://zenodo.org/) as a valid open access repo?

I don't know what a long term sustainability plan is supposed to look like, but this is from their FAQ:

> **Is my data safe with you / What will happen to my uploads in the unlikely event that Zenodo has to close?**
>
>Yes, your data is stored in CERN Data Center. Both data files and metadata are kept in multiple online and independent replicas. CERN has considerable knowledge and experience in building and operating large scale digital repositories and a commitment to maintain this data centre to collect and store 100s of PBs of LHC data as it grows over the next 20 years. In the highly unlikely event that Zenodo will have to close operations, we guarantee that we will migrate all content to other suitable repositories, and since all uploads have DOIs, all citations and links to Zenodo resources (such as your data) will not be affected.

**Comment by steveharoz** [comment]
Yeah, Zenodo is totally eligible. I've been adding repositories as people use them. Zenodo's not used it yet.
For now, I'm adding repositories sparingly because currently the javascript checks each url against each repository when the page loads. Long term (maybe for next year), I'd like to have a precomputed check against every repository listed on [the SHARE project](https://share.osf.io/sources).

Do you know of a good example project with a preregistration, experiment materials, data, analyses, and the final paper on Zenodo?

**Comment by mjskay** [comment]
I hesistate to call it a "good example", since there are messy and cobbled-together aspects to it, but an "example" would be our CHI paper from this year, which is on github and auto-archived to Zenodo (with a nice badge on the github repo): https://github.com/Michael-Fernandes/uncertainty-displays-for-transit

I mostly like Zenodo because you can set it up to auto-archive any new release of a Github repo, and it will generate a new DOI (and it uses versioning).

**Comment by mjskay** [comment]
(I should say, we used aspredicted for the pre-reg on that one, but copied it into the repo as well.)

**Comment by steveharoz** [comment]
Thanks @mjskay. I'm closing the issue for now, but I'll probably ping you with questions about zenodo later.
