### ISSUE TITLE
Update for Vis19?

### ISSUE THREAD

**Issue by mcnuttandrew** [steveharoz/open-access-vis#71]
Thanks for making this resource. In addition to being a valuable way to highlight which papers are open access and which are not, it provides a wonderful alternative to the official schedule that (in my opinion) is more useful.

I notice that the site hasn't been updated for the 2019 conference. Are you intending for this to continue to be a thing this year/in future years? I remember hearing that there were some open access changes to accepted VIS papers but i haven't really heard much about that. 

If you are intending to keep it up this year, I'd be happy to help contribute

**Comment by steveharoz** [comment]
Thanks for the comment! Collecting data for 2019 is in progress. I'm also working on some updates to the site needed due sessions now having papers from multiple tracks. Please shoot me an email (my full name at gmail) because I may need some help next week with thumbnails.

http://steveharoz.com/blog/2019/updates-for-open-access-vis-in-2019/
